ENH: Refactoring of if-statements
lmfit/lmfit-py pull request #763
Opened 2021-11-11 20:56 UTC by Anselmoo

#### Description

Refactoring of if statements in `confidence.py`, `minimizer.py`, `model.py`, and `parameter.py`

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

```shell
Python: 3.8.12 (default, Nov 11 2021, 07:35:10) 
[Clang 13.0.0 (clang-1300.0.29.3)]

lmfit: 1.0.3, scipy: 1.7.2, numpy: 1.21.4, asteval: 0.9.25, uncertainties: 3.1.6
```
###### Verification 
Have you

- [x] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

2021-11-12 04:08 UTC, newville commented
@Anselmoo I think we all appreciate the interest and effort.  I also think that an unsolicited pull request that modifies working code to match your own style preference might not be the best introduction one can make. 

@reneeotten any thoughts on this?

2021-11-12 05:12 UTC, reneeotten commented
> @Anselmoo I think we all appreciate the interest and effort. I also think that an unsolicited pull request that modifies working code to match your own style preference might not be the best introduction one can make.
> 
> @reneeotten any thoughts on this?

@newville @Anselmoo some of rewrites make sense and I'd be in favor of using them, others I don't reaaly like from cursory look. I will take a closer look hopefully in the next few days and leave some review comments on the proposed changes.

2021-11-12 13:18 UTC, newville commented
@reneeotten thanks -- that was my impression too.  I guess that means that we should do a line-by-line review of this over the next week or so (I'm not going to rush on this!) and hope that @Anselmoo is amenable to making the requested changes.

2021-11-12 13:20 UTC, Anselmoo commented
> @reneeotten thanks -- that was my impression too. I guess that means that we should do a line-by-line review of this over the next week or so (I'm not going to rush on this!) and hope that @Anselmoo is amenable to making the requested changes.

@newville @reneeotten this sounds good

2021-12-01 18:48 UTC, reneeotten requested changes
@Anselmoo sorry for the delay... I went looked through your proposed changes and left comments for the ones I don't agree with and/or have a question. Please take a look and once you make the changes / comment here, perhaps @newville can glance over it as well and we can wrap this up.

2021-12-01 18:48 UTC, reneeotten commented on lmfit/model.py
> -        # 2. modern, best-practice approach: use inspect.signature
please leave this comment

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +
please revert this block to the original; there is no benefit of doing this with respect to speed / readability

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +        ]
please revert this, this reverse logic makes it much less readable at first glance...

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +            r = r.sum()
I don't see a benefit here and am sure the changed code will work as well; to me the flow is visually easier to follow in the old code; the second check/manipulation will only happen if the first criteria is met. I'd prefer to revert.

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +            i += 1
please revert, no benefit in readability / shorter code

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +        ):
I am okay with folding the second `if`-statement in here, but don't like the formatting - I don't think all these parenthesis are actually needed or (I know the were there already...).
Can this not just become:
```
if not is_weighted and result.residual.size > 1 and '__lnsigma' in params:
```

2021-12-01 18:48 UTC, reneeotten commented on lmfit/minimizer.py
> +        result.bic = _neg2_log_likel + np.log(result.ndata) * result.nvarys
I don't follow this as the diff is hard to read; what is the actual change here? Why do we need a new function `_extracted_from_emcee_201` - unless there is a convincing argument to do this, I am not really inclined to accept this.

2021-12-03 09:24 UTC, Anselmoo commented on lmfit/model.py
> -        # 2. modern, best-practice approach: use inspect.signature
Agree

2021-12-07 02:32 UTC, reneeotten commented
@Anselmoo a few more things and then please squash your commits so there is only one left

2021-12-07 08:39 UTC, Anselmoo commented on lmfit/minimizer.py
> +            result.residual = result.residual/np.exp(params['__lnsigma'].value)
That's an excellent point

2021-12-07 08:44 UTC, Anselmoo commented on lmfit/minimizer.py
> -        # This should eventually be moved into result._calculate_statistics.
That was a mistake; good point

2021-12-07 08:51 UTC, Anselmoo commented
> @Anselmoo a few more things and then please squash your commits so there is only one left

I hope my combination of local _soft reset_, _squash_, and _push_, is working as expected.

2021-12-07 20:54 UTC, reneeotten approved these changes

2021-12-07 20:56 UTC, reneeotten commented
thanks for taking care of the review comments/changes @Anselmoo! This looks good to me - @newville can you glance over this to make sure you're also happy with the proposed changes?

2021-12-08 01:02 UTC, newville commented
@Anselmoo @reneeotten My only concern is that the change at `Model.py` line 290 should be reverted to `if len(opts) > 0:`.  All the other changes are cosmetic, but that one changes the logic.

2021-12-08 03:21 UTC, reneeotten commented
> @Anselmoo @reneeotten My only concern is that the change at `Model.py` line 290 should be reverted to `if len(opts) > 0:`. All the other changes are cosmetic, but that one changes the logic.

@newville: I don't think that statement is correct, there is no change in the logic: `if len(opts) > 0` just tests if the list exists (i.e., has at least one element), that's the same as what happens with `if opts` - right? According to `pep8` the latter is actually preferred: "For sequences, (strings, lists, tuples), use the fact that empty sequences are false".

2021-12-08 05:15 UTC, newville commented
@reneeotten part of the question is where you want a possible error to occur and what the message to say.  Please leave `if len(opts) > 0`.  

Really, I appreciate the willingness to help.  Please do not re-format working code to match a style guide.  If the two forms are equivalent, what is gained by the change?  If the two forms are not (say, someone adds some code and `opts` is no longer a sequence), then the code is broken.

2021-12-08 08:06 UTC, Anselmoo commented
@newville @reneeotten thx for your review

>If the two forms are equivalent, what is gained by the change?

Concerning this argument, the two forms (`if len(opts) > 0` vs. `if opts > 0`) are not equivalent, because `if len(opts) > 0` is redundant if statements. Just comparing the list would be enough. 

```python
>>> [ ] == True
False
```

In case, that `opts` can be also become a just an `int` or `float`,  a `raise`-statement would make sense?

But I got your point @newville, this was just for clarificaion.

2022-02-01 18:19 UTC, Anselmoo commented
@reneeotten any update?

2022-02-02 23:42 UTC, newville commented
@Anselmoo The ball is still in your court to address the existing reviews.   Revert Model line 292.  Yes, that logic change is holding up merging this.

2022-02-03 07:13 UTC, Anselmoo commented
> @Anselmoo The ball is still in your court to address the existing reviews. Revert Model line 292. Yes, that logic change is holding up merging this.

Thx for feedback @newville

2022-02-04 13:11 UTC, Anselmoo commented
I can remove the rebase, however it looks like that _five_ test will be failed in any case if this PR will be merged with the master branch.

@newville @reneeotten are there any plans to fix this in another PR or should be this fixed in this, too?

Most of the fails are linked to numeric issues [https://github.com/lmfit/lmfit-py/pull/763/checks?check_run_id=5048292287](https://github.com/lmfit/lmfit-py/pull/763/checks?check_run_id=5048292287) after specifying the `requirements`?

2022-02-04 14:03 UTC, reneeotten commented
> I can remove the rebase, however it looks like that _five_ test will be failed in any case if this PR will be merged with the master branch.

Yes, squash your commits and rebase with `master` so that you have only one commit left. There are some tests that fail indeed and this started with the latest NumPy version but only on Linux. I don't really understand where the problem originates... Of course if you know how to fix it issue (without just relaxing the criteria and/or removing the tests of course) that would be great, but it's not a prerequisite for this PR.

2022-02-17 17:17 UTC, merged

2022-02-17 17:17 UTC, reneeotten commented
thanks @Anselmoo

2022-02-17 17:21 UTC, newville commented
@Anselmoo @reneeotten thanks!