Update ConfidenceInterval class constructor parameters
lmfit/lmfit-py pull request #937
Opened 2024-01-23 05:49 UTC by Anselmoo

Defining `self.min_rel_change` in confidence.py as variable Fixes #936

#### Description

This pull request updates the constructor parameters of the ConfidenceInterval class in `confidence.py`. Specifically, it adds a new parameter called min_rel_change with a default value of 1e-5. This change addresses issue #936.

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [ ] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

2024-01-23 19:26 UTC, Tillsten commented
I fully agree with addition. I think a test showing that changing the parameter does something useful would be nice.

2024-01-24 13:54 UTC, reneeotten commented on lmfit/confidence.py
> +                maxiter=50):
also please write a more meaningful commit message

2024-01-24 16:54 UTC, Anselmoo commented on lmfit/confidence.py
> +                maxiter=50):
I agree and please also check 

```suggestion
def conf_interval(minimizer, result, p_names=None, sigmas=None, trace=False,
                  maxiter=200, verbose=False, prob_func=None, 
                  min_rel_change=1e-5):
```

it also has to be updated

2024-01-24 17:00 UTC, Anselmoo commented on lmfit/confidence.py
> +                maxiter=50):
One more thing, I had the issue with `flake8`, and i had lint it, so a few functions inputs looks different. @reneeotten is that still ok? Othwerise, I will revert it

2024-01-24 17:07 UTC, reneeotten commented on lmfit/confidence.py
> +                maxiter=50):
no, that's not okay - please revert. The way it was passed the "pre-commit" checks so there is no reason to change them. We want minimal diffs so no unneeded/unrelated changes please.

2024-01-24 17:28 UTC, Anselmoo commented on lmfit/confidence.py
> +                maxiter=50):
Sorry, I struggled with `flake8` indentations.

2024-01-25 02:43 UTC, reneeotten requested changes
thanks @Anselmoo ; it looks like that correcting the position of the new argument fixed the tests as well. This looks good to me, except for a few changes that are required in the docstring.

2024-01-25 02:43 UTC, reneeotten commented on lmfit/confidence.py
> +            The sigma-levels to find (default is [1, 2, 3]). See Notes below.
remove the "See Notes below."

2024-01-25 02:43 UTC, reneeotten commented on lmfit/confidence.py
> +            Maximum of iteration to find an upper limit (default is 200).
it appears that the default is "50" instead of "200"?

2024-01-25 02:43 UTC, reneeotten commented on lmfit/confidence.py
> +            If there are less than 2 variables or if the stderrs are not
"2" --> "two" (it's a number below ten and should be written out)

2024-01-25 02:43 UTC, reneeotten commented on lmfit/confidence.py
> +        """
should be a newline before closing the docstring

2024-01-25 21:22 UTC, newville commented
@Anselmoo Thanks - that looks good to me.

2024-01-26 04:12 UTC, merged