Allow model opts
lmfit/lmfit-py pull request #950
Opened 2024-04-08 02:02 UTC by newville

#### Description

This restores the behavior of setting a non-default keyword value for a Model function argument when creating a Model.  That is, in 1.3.0, 

```
from lmfit import Model
from lmfit.lineshapes import step

mymodel  = Model(step, form='erf')
```

could sometimes fail to set the form to `erf`.  This is true in `StepModel`, for example, as it set the independent variables to ['x'].

The fix here is sort of "belt and suspenders" in that: the form above should normally work in 1.3.0, but now that new default value (held in `Model.opts = {'form': 'erf'}`) is used, and then any independent variables are set, and then any runtime keyword arguments.
 
See #947 

Not being able to leave well enough alone, I also tweaked `Model.__repr__()` to use `Model._reprsting()` and to use `long=True` by default.   With this, for example, the repr for `StepModel` will always show the `form`.

This can be squashed-and-merged or the repr string change can be removed.

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:35:23) [Clang 15.0.7 ]

lmfit: 1.3.0.post2+gcf2626b.d20240407, scipy: 1.12.0, numpy: 1.26.4, asteval: 0.9.32, uncertainties: 3.1.7

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [x] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [x] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [x] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

2024-04-10 14:05 UTC, newville commented
@reneeotten   I'd like to merge this (or a reviewed version of it) and tag as 1.3.1 over the next week or so.   Any objections?

2024-04-10 16:31 UTC, reneeotten commented
> @reneeotten   I'd like to merge this (or a reviewed version of it) and tag as 1.3.1 over the next week or so.   Any objections? 

@newville I'll take a look tonight after work.

2024-04-15 00:58 UTC, reneeotten requested changes
sorry for the delay @newville .... Changes look fine to me, the only suggestion I would have is to completely remove all type annotations in the added test and perhaps reorganize/minimize the commits a bit so that it's clear what is fixing the two issues. But that does likely require a bit of git-voodoo and I know you're not so keen on that ;) Anyway, the code changes look good to me and to be honest you know that code much better than me - so feel free to merge!

2024-04-15 00:58 UTC, reneeotten commented on tests/test_model.py
> +    def __init__(self, degree: int = 1):
remove type annotations

2024-04-15 00:58 UTC, reneeotten commented on tests/test_model.py
> +    def __name__(self) -> str:
remove type annotation

2024-04-15 00:58 UTC, reneeotten commented on tests/test_model.py
> +    def argnames(self):   # for Py39+:  -> list[str]:
I'd suggest to completely remove; I don't think there are any plans to add type annotations anytime soon...

2024-04-15 02:53 UTC, newville commented
@reneeotten Thanks!  I backed up and did a forced push for one commit to address #953.  I think this is probably OK to leave as a few separate commits rather than squash-and-merge.  Assuming the tests pass, I'll plan on merging in a day or so.  
I would then rebase to get #952 (maybe with more tweaks) merged, then call that 1.3.1.

2024-04-15 17:36 UTC, newville commented
OK, merging this...

2024-04-15 17:36 UTC, merged